---
installed_packages:
  - gettext
  - git
  - gpg
  - iperf
    #- libevent
  - mcrypt
  - nmap
    # - node
    #  - nvm
    #  - php
    #- ssh-copy-id
    #- cowsay
    #- readline
  - openssl
  - pv
  - wget
  - wrk
