---
git_name: "philcryer"
git_email: "phil@philcryer.com"

code_directory: $HOME/devel

downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/philcryer/dotty.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/devel

dotfiles_files:
  - .bash_profile
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc
