---
- name: Ensure home bin directory
  file:
    path: "${HOME}/bin"
    state: directory

- name: Ensure code dictory exists
  file:
    path: "{{ code_directory }}"
    state: directory

- name: Ensure Downloads directory exists
  file:
    path: "${HOME}/Downloads"
    state: directory
