---
- name: Checkout dotfiles repo
  git:
    repo: "{{ dotfiles_giturl }}"
    dest: "{{ code_directory }}/dotfiles/"
    clone: yes
    update: yes

- name: Install dotfiles
  synchronize:
    src: "{{ code_directory }}/dotfiles/{{ item }}"
    dest: "~/{{ item }}"
    checksum: yes
    archive: no
  with_items:
    - "{{ dotfiles_files }}"
