---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Install a list of packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ installed_packages }}"
  become: yes

- name: Ensure SpaceVim fonts dir exists
  file:
    path: ~/.local/share/fonts
    state: directory
  when: spacevim_dir.stat.exists == false

- name: Extract SpaceVim fonts
  unarchive:
    src: "{{ downloads }}/SourceCodePro.zip"
    dest: ~/.local/share/fonts
  when: spacevim_dir.stat.exists == false

- name: Remove SpaceVim fonts zip
  file:
    path: "{{ downloads }}/SourceCodePro.zip"
    state: absent
