---
- name: Ensure home bin directory
  file:
    path: ${HOME}/bin
    state: directory

- name: Ensure code dictory exists
  file:
    path: ${HOME}/{{ code_directory }}
    state: directory

- name: Check for non-standard Downloads directory
  stat:
    path: ${HOME}/Downloads
  register: stat_downloads_dir

- name: If non-standard Downloads directory exists, symlink it
  file:
    src: ${HOME}/Downloads
    path: ${HOME}/downloads
    state: link
  when: stat_downloads_dir.stat.exists == True

  #- name: MacOS specific tasks
  #include_tasks: macos.yml
  #when: ansible_distribution == 'MacOSX'

- name: Linux specific tasks
  include_tasks: linux.yml
  when: ansible_system == 'Linux'
