---
- hosts: all
  connection: local
  gather_facts: true

  vars_files:
      - "group_vars/all.yml"
      - "group_vars/{{ ansible_system|lower }}.yml"

  roles:
    - role: geerlingguy.homebrew
      when: ansible_distribution == 'MacOSX'
      tags: ['osx']

      #- role: elliotweiser.osx-command-line-tools
      #when: ansible_distribution == 'MacOSX'
      #tags: ['osx']
      #- role: geerlingguy.dotfiles
      #when: configure_dotfiles
      #tags: ['dotfiles']
      #- role: geerlingguy.mas
      #when: mas_installed_apps
      #tags: ['mas']

  tasks:
    - include_tasks: "tasks/main.yml"
    - include_tasks: "tasks/dotfiles.yml"
    - include_tasks: "tasks/{{ ansible_system|lower }}.yml"
