---
- hosts: all
  connection: local
  become: true

  vars_files:
    - vars/common.yml
    - vars/{{ ansible_distribution|lower }}.yml

  roles:
      #  - role: elliotweiser.osx-command-line-tools
      #when: ansible_distribution == 'MacOSX'
    - role: geerlingguy.homebrew
      when: ansible_distribution == 'MacOSX'

      #- role: geerlingguy.dotfiles
      #when: configure_dotfiles
      #tags: ['dotfiles']
      #- role: geerlingguy.mas
      #when: mas_installed_apps
      #tags: ['mas']

  tasks:
    - include_tasks: tasks/main.yml

      # - include_tasks: tasks/sudoers.yml
      #when: configure_sudoers

      # - include_tasks: tasks/terminal.yml
      #when: configure_terminal

      #- include_tasks: tasks/osx.yml
      #when: ansible_distribution == 'MacOSX'
      #tags: ['osx']

      #- include_tasks: tasks/extra-packages.yml
      #tags: ['extra-packages']

      #- name: Run configured post-provision ansible task files.
      #include_tasks: "{{ outer_item }}"
      #loop_control:
      #  loop_var: outer_item
      #with_fileglob: "{{ post_provision_tasks|default(omit) }}"
